### ISSUE TITLE
Long alabels overlap

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/InteractiveChaos.jl#13]
![grafik](https://user-images.githubusercontent.com/65158285/89276379-e0269800-d643-11ea-87c8-83c7c4aadc25.png)

As you can see in this picture, relatively long `alabels` overlap in the Makie app. Maybe introduce some soft wrapping once the text would go "out of bounds".

**Comment by Datseris** [comment]
I am not aware of a Makie.jl option that can do this text warping. How about you add `\n` to the text, so that a break line exists? Does it work then?

**Comment by fbanning** [comment]
Yep, that works.
