### ISSUE TITLE
Allow a stopping function in `abm_video`

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/InteractiveChaos.jl#31]
Unsure if we should allow this or not, but the Agents.jl Opinion Spread example uses its `rununtil` stopping function to break the animation loop. Can/should we allow this? Or is there a way to do this with a custom `scheduler` perhaps?

**Comment by Datseris** [comment]
quite low priority for me for sure

**Comment by Libbum** [comment]
Yeah, I tend to agree. I'm going to add a seed into the example and set the frames to the stopping condition of a pre-ran model.
