### ISSUE TITLE
Agents: kwargs to axis

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/InteractiveChaos.jl#33]
It would be nice to be able to send at least a few kwargs to the main axis in `abm_plot` and `abm_video` (at least).
Similar to scatterkwargs, can we supply an axiskwargs tuple in the future?

For example, if I don't want to have xticks visible, or I want to change their value in some way, at present the only way to do this is a completely custom plot.

**Comment by Datseris** [comment]
you can still do it:
```
fig, abmstepper = abm_plot(...)
ax = content(fig[1,1]) # gives the axis
ax.xticksvisible = false
```

**Comment by Libbum** [comment]
in `abm_video`?

**Comment by Datseris** [comment]
yeah in abm_video not possible, feel free to modify the standing PR #32 to accept keywords propagated to the axis.
