### ISSUE TITLE
Cannot use interactive_abm

### ISSUE THREAD

**Issue by yanyuan-wang** [JuliaDynamics/InteractiveChaos.jl#9]
Hi, after I load `InteractiveChaos`,  I have no access to the function `interactive_abm`, does anyone know why this happens?

**Comment by Datseris** [comment]
Can you try doing:
```
using InteractiveChaos, Agents
```
and report back? All functions require you to also load the appropriate dynamical module (i.e. the functions are provided dynamically once you load the appropriate model, so that `InteractiveChaos` does not install Agents+Billiards+DynamicalSystems )

**Comment by Datseris** [comment]
This is what I've tried to explain in https://juliadynamics.github.io/InteractiveChaos.jl/dev/#Usage-1 , do you think I can do a better job?

**Comment by yanyuan-wang** [comment]
![image](https://user-images.githubusercontent.com/61305781/87549758-c8ad5c80-c6e0-11ea-9f81-dcb0b0507e49.png)

Hi, I'm sorry. It still does not work for me. In fact, I just want to replicate the example given in https://juliadynamics.github.io/InteractiveChaos.jl/dev/agents/#InteractiveChaos.interactive_abm. 

And I saw someone has the same error like me, in https://discourse.julialang.org/t/agents-jl-agentsplots-jl-interactivechaos-jl-errors/42941.

Thx in advance!

**Comment by Datseris** [comment]
Alright, can you please post your package versions?

**Comment by yanyuan-wang** [comment]
![image](https://user-images.githubusercontent.com/61305781/87556191-f0a0be00-c6e8-11ea-8a97-c2cdec4619a6.png)
The attached is my package versions FYR.

**Comment by Datseris** [comment]
`interactive_abm` was added in version 0.8 of interactive chaos, you are at least 5 versions behind. On current version I cannot reproduce your problem:

```
(@v1.4) pkg> st InteractiveChaos
Status `C:\Users\m300808\.julia\environments\v1.4\Project.toml`
  [81850811] InteractiveChaos v0.9.0 [`C:\Users\m300808\.julia\dev\InteractiveChaos`]

julia> using InteractiveChaos, Agents

julia> interactive_abm
interactive_abm (generic function with 2 methods)
```

**Comment by yanyuan-wang** [comment]
Problem solved, thank you!

**Comment by mthelm85** [comment]
When I ```Pkg.add``` InteractiveChaos, I get v0.3.2. Have the new versions been tagged for release?

**Comment by Datseris** [comment]
> When I Pkg.add InteractiveChaos, I get v0.3.2. Have the new versions been tagged for release?

Yes of course, all versions in the following image are guaranteed to be tagged: 

![image](https://user-images.githubusercontent.com/19669089/87683793-c64f0f00-c781-11ea-8d1c-8b2f82378053.png)


There has to be something holding your packages. Try to do `up` and if it still doesn't work try to do `add InteractiveChaos@0.9` to get an error message of exactly what is holding the versions back.

**Comment by mthelm85** [comment]
`up` worked. Thanks! I'm still getting errors though in the plotting, I'll come back to this at a later date and post a MWE.

**Comment by Datseris** [comment]
Yeap but be sure to post it in the appropriate repo. AgentsPlots.jl is completely independent from InteractiveChaos. One uses Plots.jl and the other Makie.jl. Also, AgentsPlots.jl will be completely re-written to use Makie.jl when a stable version of Makie is out.
